name: Build Windows

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: version
        run: |
          echo ::set-output name=describe::$(git describe --tags --dirty)
        shell: bash
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-5152-win64_msvc2019_64-QtCache
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          arch: win64_msvc2019_64
          modules: qtwebglplugin
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - run: env
        shell: bash
      - name: qmake
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          ${{ env.Qt5_DIR }}\bin\qmake.exe -config release QuteScoop.pro
        shell: cmd
      - name: nmake install
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          nmake.exe install
        shell: cmd
      - name: windeployqt
        working-directory: DIST-win64
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          ${{ env.Qt5_DIR }}/bin/windeployqt.exe .
        shell: cmd
      - name: Upload Makefile
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: "Debug: Win-${{ steps.version.outputs.describe }}-Makefile"
          path: ./Makefile*
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: QuteScoop-Win-${{ steps.version.outputs.describe }}
          path: ./DIST-win64
