name: Build Mac

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get tag/branch
        id: tag
        run: echo ::set-output namei=TAG::${GITHUB_REF/refs\/tags\//}
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.8.0
        with:
          version: '5.12.8'
      - run: qmake QuteScoop.pro
      - run: make 
      - run: make install
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: QuteScoop-Mac-${{ steps.tag.outputs.TAG }}-${{ github.sha }}.zip
          path: ./DIST-macx64
