name: Build Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get tag/branch
        id: tag
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get update
      - name: Install GLU
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libglu1-mesa-dev
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.8.0
        with:
          version: '5.12.8'
      - run: qmake QuteScoop.pro
      - run: make -j$(nproc)
      - run: make install
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
      - run: chmod +x ./DIST-unix64/QuteScoop ./DIST-unix64/QuteScoop.sh
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: QuoteScoop-Linux-${{ steps.tag.outputs.SOURCE_NAME }}-${{ github.sha }}.zip
          path: ./DIST-unix64
