name: Build Windows

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get tag/branch
        id: tag
        run: echo ::set-output namei=TAG::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.8.0
        with:
          version: '5.12.8'
          arch: win64_mingw81
          modules: qtwebglplugin
      - run: qmake QuteScoop.pro
      - run: make 
      - run: make install
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: QuteScoop-Win-${{ steps.tag.outputs.TAG }}-${{ github.sha }}.zip
          path: ./DIST-win32
