name: Build Mac

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: version
        run: |
          echo ::set-output name=describe::$(git describe --tags --dirty)
        shell: bash
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - run: qmake -config release QuteScoop.pro
      - name: Upload Makefile
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: "Debug: Mac-${{ steps.version.outputs.describe }}-Makefile"
          path: ./Makefile*
      - run: make 
      - run: make install
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: QuteScoop-Mac-${{ steps.version.outputs.describe }}
          path: ./DIST-macx64
