name: Build Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
