name: Build Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get tag/branch
        id: tag
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get update
      - name: Install GLU
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libglu1-mesa-dev
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
#      - run: cd ../Qt && ./configure -static -prefix ../Qt && make
      - run: env
# Qt5_Dir=/home/runner/work/qutescoop/Qt/5.15.2/gcc_64
# QT_PLUGIN_PATH=/home/runner/work/qutescoop/Qt/5.15.2/gcc_64/plugins
      - run: ls "$Qt5_Dir"
      - run: ls "$Qt5_Dir"/lib/
      - run: ls "$QT_PLUGIN_PATH"/*
      - run: qmake -config release QuteScoop.pro
      - run: make -j$(nproc)
      - run: make install
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
      - run: chmod +x ./DIST-unix64/QuteScoop ./DIST-unix64/QuteScoop.sh
      - run: ldd ./DIST-unix64/QuteScoop
      - run: mkdir ./DIST-unix64/lib
      - run: ldd ./DIST-unix64/QuteScoop | grep "=> /" | awk '{print $3}' | grep -E 'libQt|libgcc|libstdc|libicu|libGL|libxcb|libX' | xargs -I '{}' cp -v '{}' ./DIST-unix64/lib/
      - run: cp "$Qt5_Dir"/lib/libQt5DBus.so.5 "$Qt5_Dir"/lib/libQt5XcbQpa.so.5 ./DIST-unix64/lib/
      - run: mkdir ./DIST-unix64/platforms
      - run: ls "$QT_PLUGIN_PATH"/platforms/libqxcb*.so*
      - run: ls ./DIST-unix64/platforms
      - run: cp "$QT_PLUGIN_PATH"/platforms/libqxcb*.so* ./DIST-unix64/platforms
      - run: cp -ar "$QT_PLUGIN_PATH"/xcbglintegrations ./DIST-unix64/
      # https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
      - name: 'Tar files'
        run: tar --directory=./DIST-unix64 -cvf QuteScoop-Linux-${{ steps.tag.outputs.SOURCE_NAME }}-${{ github.sha }}.tar ./
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: QuteScoop-Linux-${{ steps.tag.outputs.SOURCE_NAME }}-${{ github.sha }}
          path: QuteScoop-Linux-${{ steps.tag.outputs.SOURCE_NAME }}-${{ github.sha }}.tar
